### ISSUE TITLE
Seated tracking mode

### ISSUE THREAD

**Issue by evovinetu** [rwebber/kinect2share#2]
Is it possible to switch skeleton tracking to Seated Mode?
[Tracking Modes](https://msdn.microsoft.com/en-us/library/hh973077.aspx)

**Comment by rwebber** [comment]
It doesn't look difficult. 
Since I am using an addon for connecting with the Kinect, it would be best to have the addon add support for this feature. I do not have time to investigate making this change at this time.
But is the addon adds it I will happily extend Kinect2share.
This is the addon: https://github.com/elliotwoods/ofxKinectForWindows2
